adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Barcode Scanner 4.7.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Bible for Kids 1.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Black theme 1.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Brazil Cup 2014 1.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Bubbles 2.27.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Calendar 201404014.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Call Blocker 4.2.48.20.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Candy Crush Saga 1.32.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Car Parking 1.0.8.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Cart??o F??cil Free 1.1.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Chennai Express - Escape from Rameshwaram 8.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Chennai Route Check 5.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Chennai Suburban 4.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Chrome 35.0.1916.141.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Clean calendar widget Pro 4.14.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Cleartrip 4.2.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Cloud Print 1.5.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Codecs for Archos Video 2.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Contacts Sync Fix 1.47.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Courier Tracking India 3.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Desk Notes 1.3.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Diamond Dash 3.0.2 (30210).apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\DiskInfo 4.5.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Do Not Disturb 2.2.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Drive 1.3.144.25.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Dropbox 2.4.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Easy SMS 3.5.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Easy Unrar Lite 3.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\eBay 2.6.1.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Elegance 1.3.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\eRail.in 1.0.13.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\ES Classic Theme 1.05.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\ES File Explorer 3.1.7.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Expense Manager 2.1.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Facebook 10.0.0.28.27.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Fast File Transfer 1.2.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Financial Calculators 2.0.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Flickr 3.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Flipkart 2.5.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Free SMS India 7.8.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Gallery 1.1.40012.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Gmail 4.8 (1167183).apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\GNotes 0.9.40.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google Play Music 5.5.1514O.1185867.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google Play services 4.4.52 (1174655-036).apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google Play Store 4.8.20.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google Search 3.4.16.1149292.arm.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google Text-to-speech Engine 3.1.3.1162895.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Google+ 4.4.2.68956353.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\GoPro 2.4.87.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Hangouts 2.1.224 (1212213-30).apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Icon Changer free 3.1.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\iMobile 3.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\IndexBook 1.0.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Jetpack Joyride 1.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Just For Laughs 1.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Justdial 3.4.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Kids Numbers and Math Lite 1.37.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\KitKat HD Theme 1.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\KitKat StatusBar 1.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\KitKat Theme 1.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Learn Hindi 2.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\LinkedIn 3.3.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Lockscreen Policy 1.3.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Lucky Patcher 4.3.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Maps 8.1.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MediaFire 1.1.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Messenger 6.0.0.27.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\mGerrit 2.10.008.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Microsoft Remote Desktop 8.0.6.24867.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MIUI X4 THEME FREE 1.9.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MobiKwik 4.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Mobile Number Locator 1.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Month Calendar Widget 1.6.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MX Player 1.7.28.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MX Player Codec (ARMv7 NEON) 1.7.28.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\MY BSNL 1.05.02.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\My Diet Coach 3.0.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\My Tracks 2.0.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Notes Lite 1.0.23.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Office Talk Free 2.0.32.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\OLX 3.3.8.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\One Touch Location 4.1.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\OneDrive 2.5.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Pet Rescue Saga 1.20.5.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Phone and SIM Info 1.5.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Photo Resizer 1.1.9.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Picasa Tool 7.3.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\PicSpeed Wallpapers 3.2.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Pixlr Express 2.2.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\PNR status and train info 0.12.43.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\ProCapture 1.7.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Profile Scheduler 3.0.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\QuickPic 3.4.9.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Quikr 4.8.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\RacingMoto 1.2.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Real Time GPS Tracker 0.9.65.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\RealCalc 1.7.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\ROM Toolbox Pro 5.8.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Skype 4.9.0.45564.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Slots Vacation 1.44.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Smart Voice Recorder 1.7.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\SMS Backup & Restore 7.12.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Speedtest 3.1.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Subway Surf 1.24.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\SugarSync 4.1.1.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\SwiftKey 5.0.0.72.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\TalkBack 3.5.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Tamil Bible 2.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Tamil Comedy And Punch Dialogue 3.5.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Tamil Radio 2.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Tamil Songs 7.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Terminal Emulator 1.0.61.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Text Fairy 1.1.22.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\The Table 1.07.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Titanium Backup 6.1.5.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Torrent Search (by Transdroid) 1.10.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Tower Blocks Classic 1.0.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\tTorrent 1.3.3.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Ulysse Speedometer 1.9.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Unblock Me FREE 1.4.2.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Unit Converter 2.8.5.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\User Dictionary Manager (UDM) 4.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Viral Lite 2.4.6.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\VNC Viewer 1.2.6.109857.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Watch Tamil Movies Free 3.9.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Weather & Clock Widget 3.8.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\WhatsApp 2.11.238.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Wifi Analyzer 3.7.1.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\WiFi Channel Analyzer (free) 2.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\WPS Office (Kingsoft Office) 6.0.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\XBMC 13.0.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Yahoo Mail 4.0.2.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\YouTube 5.7.38.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\YouTube Downloader 3.6.4.apk"
adb install -r "c:\Users\sajam\Mobile\Nexus 4\Apps\Zedge 3.5.apk"
